//-----------------------------------------------------------------------
// <copyright company="Nuclei">
//     Copyright (c) - Nuclei. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
//
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

using System.Runtime.CompilerServices;

/*
 * THIS IS A GENERATED FILE. DO NOT MAKE CHANGES IN THIS FILE BECAUSE ANY
 * CHANGES WILL BE UNDONE THE NEXT TIME THE FILE IS GENERATED!
 */

[assembly: InternalsVisibleTo("Nuclei.AppDomains, PublicKey=0024000004800000940000000602000000240000525341310004000001000100115ccaaaf6cab0651b9dd6385972385f22c0da0b48f3d74a52cd16fdca5febf11f499dacde2eace213b49b3ddd935af3f26ec94e7f9aed9095eddf4885ae492247ae1ffaa0d4402499b4f83f0581287a54577527312843cc6fd25f257172cf69720364d3c0fa8caded5e2b4cab1e5a21b63eea2422c35efc4c8f0df5fdedbfb4")]
[assembly: InternalsVisibleTo("Test.Unit.Nuclei, PublicKey=0024000004800000940000000602000000240000525341310004000001000100115ccaaaf6cab0651b9dd6385972385f22c0da0b48f3d74a52cd16fdca5febf11f499dacde2eace213b49b3ddd935af3f26ec94e7f9aed9095eddf4885ae492247ae1ffaa0d4402499b4f83f0581287a54577527312843cc6fd25f257172cf69720364d3c0fa8caded5e2b4cab1e5a21b63eea2422c35efc4c8f0df5fdedbfb4")]
[assembly: InternalsVisibleTo("Test.Unit.Nuclei.Communication, PublicKey=0024000004800000940000000602000000240000525341310004000001000100115ccaaaf6cab0651b9dd6385972385f22c0da0b48f3d74a52cd16fdca5febf11f499dacde2eace213b49b3ddd935af3f26ec94e7f9aed9095eddf4885ae492247ae1ffaa0d4402499b4f83f0581287a54577527312843cc6fd25f257172cf69720364d3c0fa8caded5e2b4cab1e5a21b63eea2422c35efc4c8f0df5fdedbfb4")]
[assembly: InternalsVisibleTo("Test.Unit.Nuclei.Configuration, PublicKey=0024000004800000940000000602000000240000525341310004000001000100115ccaaaf6cab0651b9dd6385972385f22c0da0b48f3d74a52cd16fdca5febf11f499dacde2eace213b49b3ddd935af3f26ec94e7f9aed9095eddf4885ae492247ae1ffaa0d4402499b4f83f0581287a54577527312843cc6fd25f257172cf69720364d3c0fa8caded5e2b4cab1e5a21b63eea2422c35efc4c8f0df5fdedbfb4")]
[assembly: InternalsVisibleTo("Test.Unit.Nuclei.Diagnostics, PublicKey=0024000004800000940000000602000000240000525341310004000001000100115ccaaaf6cab0651b9dd6385972385f22c0da0b48f3d74a52cd16fdca5febf11f499dacde2eace213b49b3ddd935af3f26ec94e7f9aed9095eddf4885ae492247ae1ffaa0d4402499b4f83f0581287a54577527312843cc6fd25f257172cf69720364d3c0fa8caded5e2b4cab1e5a21b63eea2422c35efc4c8f0df5fdedbfb4")]
[assembly: InternalsVisibleTo("Test.Unit.Nuclei.Fusion, PublicKey=0024000004800000940000000602000000240000525341310004000001000100115ccaaaf6cab0651b9dd6385972385f22c0da0b48f3d74a52cd16fdca5febf11f499dacde2eace213b49b3ddd935af3f26ec94e7f9aed9095eddf4885ae492247ae1ffaa0d4402499b4f83f0581287a54577527312843cc6fd25f257172cf69720364d3c0fa8caded5e2b4cab1e5a21b63eea2422c35efc4c8f0df5fdedbfb4")]
[assembly: InternalsVisibleTo("Moq, PublicKey=00240000048000009400000006020000002400005253413100040000010001009f7a95086500f8f66d892174803850fed9c22225c2ccfff21f39c8af8abfa5415b1664efd0d8e0a6f7f2513b1c11659bd84723dc7900c3d481b833a73a2bcf1ed94c16c4be64d54352c86956c89930444e9ac15124d3693e3f029818e8410f167399d6b995324b635e95353ba97bfab856abbaeb9b40c9b160070c6325e22ddc")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2, PublicKey=0024000004800000940000000602000000240000525341310004000001000100c547cac37abd99c8db225ef2f6c8a3602f3b3606cc9891605d02baa56104f4cfc0734aa39b93bf7852f7d9266654753cc297e7d2edfe0bac1cdcf9f717241550e0a7b191195b7667bb4f64bcb8e2121380fd1d9d46ad2d92d2d15605093924cceaf74c4861eff62abf69b9291ed0a340e113be11e6a7d3113e92484cf7045cc7")]
